language: python
python:
    - "2.7"
    - "3.4"
cache: apt
before_install:
    - pip -q install pytest pytest-cov codecov coveralls

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=.

after_success:
    - codecov
    - coveralls
